### ISSUE TITLE
Pixel calibration

### ISSUE THREAD

**Issue by mcib3d** [clij/clij2#15]
Hi,

It seems that the plugins does not carry pixel calibration from the input image to the processed image, I tested with 3D Median in a sphere.

Best,

Thomas

**Comment by haesleinhuepf** [comment]
Hey Thomas @mcib3d ,

yes, [CLIJ does not take physical units into account](https://clij.github.io/clij-docs/faq#physical_units). There are two intentions behind: 1) As this is a clear rule, nobody has to read the documentation of particular plugins to find out if parameter units are pixels of microns or whatever. It's always pixels. 2) The effort for respecting physical units is high. There are quite some operations in CLIJ where I wouldn't know how to implement this at all. Just think of [distance- and touch-matrices for drawing meshes](https://clij.github.io/clij2-docs/md/tribolium_morphometry/). How could I transfer knowledge about physical pixel size between such operations? And how could this be done without confusing the user? I've seen ImageJ2 developers struggling with this for years and that's why I decided to not dig into this. As soon as they come up with a resaonable solution, I could implement an analogous one for CLIJ. I keep this issue as enhancment. :-)

Thanks for the feedback!

Cheers,
Robert

**Comment by mcib3d** [comment]
Hi Robert,

Thanks, I understand, I will take this into account for the tapas protocols, usually I saved the calibration  of the input, do some processing and segmentation then put back the calibration to the final labelled image.

Thomas
