### ISSUE TITLE
rotate3D uses radians instead of degrees in Jython (Docs error)

### ISSUE THREAD

**Issue by artgolden** [clij/clij2#59]
Hi!

I have found that when calling `clij2.rotate3D()` function from Jython in Fiji the angles need to be provided in radians. However they should be provided in degrees according to [documentation](https://clij.github.io/clij2-docs/reference_rotate3D).

I am using Fiji 2.3.0/1.53q with up to date CLIJ plugins.

**Comment by haesleinhuepf** [comment]
Hi @artgolden ,

thanks for reporting thiis! It was actually not a docs-error but an actual mistake. Thus, when you update clij2, you may have to change your code. The functions rotate2d and rotate3d take angles in degrees since the just released clij2 2.5.3.0.

Let me know if it works for you!

Thanks again!

Best,
Robert
